# .github/workflows/build-and-release.yml
name: Build PDFs and Create Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Release and Upload PDFs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'latest'
          files: |
            Course Summary/course material.pdf
            Functions/functions.pdf
            Cheat Sheet/cheat sheet.pdf
            Compressed Summary/compressed summary.pdf
            OS Tutorials.pdf
            OS Lectures.pdf